language: "perl"

install:
  - cpanm -v --installdeps --notest .
  - sudo apt-get install -y librsync-dev

script: "perl Build.PL; ./Build test"

notifications:
  irc:
    channels:
      - "chat.freenode.net#syncdiff"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{commit}) : %{message} Build details: %{build_url} "

