#!/usr/bin/perl

###########################################################################
# Copyright (C) 2014  John 'Warthog9' Hawley                              #
#                         jhawley@redhat.com                              #
#                         warthog9@eaglescrag.net                         #
#                                                                         #
# This file is originally part of SyncDiff(erent).                        #
#                                                                         #
# This library is free software; you can redistribute it and/or           #
# modify it under the terms of the GNU Lesser General Public              #
# License as published by the Free Software Foundation; either            #
# version 2.1 of the License, or (at your option) any later version.      #
#                                                                         #
# This library is distributed in the hope that it will be useful,         #
# but WITHOUT ANY WARRANTY; without even the implied warranty of          #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU       #
# Lesser General Public License for more details.                         #
#                                                                         #
# You should have received a copy of the GNU Lesser General Public        #
# License along with this library; if not, write to the:                  #
#    Free Software Foundation, Inc.                                       #
#    51 Franklin Street                                                   #
#    Fifth Floor                                                          #
#    Boston, MA  02110-1301                                               #
#    USA                                                                  #
#                                                                         #
# Or, see <http://www.gnu.org/licenses/>.                                 #
###########################################################################

use strict;
use warnings;

use Plack::Util;
use Getopt::Long;
use Data::Dumper;

MAIN: {
    my %opts;
    GetOptions( \%opts, "backend=s", "psgi=s", "help" );

    if ( $opts{help} ) {
        display_help();
        exit(0);
    }

    run(\%opts);
}

sub run {
    my $args = shift;
    my $psgi = $args->{psgi};

    #ENV info
    my $env = {};
    if ( $args->{backend} =~ /(:cgi|fcgi)/i ) {
        require 'Plack::Loader';
        my $app = Plack::Util::load_psgi($psgi);
        Plack::Loader->auto->run($app);
    }
    else {
        my $app = do($psgi);
        Plack::Util::run_app $app, $env;
    }
}

sub display_help {
    print STDOUT << 'HELP'
    It helps to run PSGI app as FCGI/CGI

    --backend=[fcgi|cgi|psgi]
    --psgi=/path/to/psgi/file

HELP
}